secret:
    databaseUrl: ENC[AES256_GCM,data:47m5YhBD9foCERBO3xBff8uT98Y6XR6oKzf1MmQZsQTcdux+wl5PLoKxiu/gfTlDQcCz04Sy2aKHE2twr24l/+nQl4gY6luHhfUERRazHwZ91eCeHaSfNoMfHOXrwmoiFQ==,iv:tyhV04JMeNuyH0lHQQxNeow1+XsUK4wXsFw5p4aFNKU=,tag:RB0DL6a2xDd5FsaJtBrD1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFck5JKzdNc1lmSG54WFh3
            c1NaOTJQNU9yVDBrMTJjYWcwM2plS2dnaHl3CmN1Qm1GQ2kzQ2hEbEJ1bHREZDdo
            VEtPTUNHdkdxNHREZmJwa0pFVFpXZ3MKLS0tIDRNQnR0a1ByT0dHSkxoZDd0bXox
            VFFudzUwejVSMGlGMzhTb3ZjbkFDZmsK+DtrEozSFeGivONFH4YrHAz2LZGdsPDy
            vx+MkxKKOjfhcKvRSGQgJtfQ/WQJ89XBN0OhLjtM5sSWhWRk3ThQxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j8rjscrrgm5jyl29peh5gqnmxx9qv795msdat33aa7qu3kqe5eysstlzzr
    lastmodified: "2026-07-16T22:19:07Z"
    mac: ENC[AES256_GCM,data:mbCZYDT8KBcrwUC9LQ0YRCsWrTTfAwwYk9qP/0ggsADmzNQSqRSWK2u2yFk78BdNntGSTrxXP0mS9WryAQ+Q7ajXQT6n1570jg9lDhbfqTW5SSj0Jy+qst65eoNLRWzcsG5pfb59r20MYZgINvikljgFR5o601hIIjeDjcvkFh4=,iv:HNIpb0/MO9hQc29nYsZ5NMwUznopqsLFUsMplIqaA5A=,tag:bfuJzFdJmGIA5kQpbioveg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
