apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: backend
          image: ${IMAGE}
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "120m"
              memory: "310Mi"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          startupProbe:
            httpGet:
              path: app/health
              port: 3001
            failureThreshold: 12    # 12 × 5 сек = 1 минута на старт
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: app/health
              port: 3001
            initialDelaySeconds: 0
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: app/ready
              port: 3001
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: default
  labels: 
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
    - name: http
      port: 3001
      targetPort: 3000
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack   # ← должен совпадать с именем release Helm
spec:
  selector:
    matchLabels:
      app: backend-api
  endpoints:
    - port: http      # имя порта из Service
      path: /metrics
      interval: 15s