apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
    - type: Container
      default:          # применяется если limits не указан
        cpu: "60m"
        memory: "240Mi"
      defaultRequest:   # применяется если requests не указан
        cpu: "50m"
        memory: "200Mi"
      max:              # Pod не может запросить больше
        cpu: "500m"
        memory: "500Mi"