secret:
    dbName: ENC[AES256_GCM,data:eDOJNzg=,iv:BrLIBw5u9irwUzyidCYOWEIIFXhrqoyrbOymiG5IlQ4=,tag:OGdqjBkaT795yg9HvU8kgw==,type:str]
    dbUser: ENC[AES256_GCM,data:QyTLmHSpzZeoWA==,iv:G4RlbBL8eWblZjAOR74yVybDDSsXBgxVmbMgdYPbaG0=,tag:s4a8jYTSaFAKPjLIl4gerQ==,type:str]
    dbPassword: ENC[AES256_GCM,data:kxrYm/2EnpDLa3vQrAcihw==,iv:fkeh4fhtWO74Jk5lUAkzanuFhedCRdfVg+5fNJ9j3cU=,tag:A5s9JCcxAipeE+B1v6IDKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aUlveVZjL2ZoV3d5MUNT
            UFl0eEg3L1dQRHQ0Y01kZ0xuQ1BLS0JubHpzCkZMQVNaSDMyd2JVQ3czWWpweWxv
            TlM4ampWYmFWT1l0bTUxSGFYZHZXdUkKLS0tIDIrcTZaeDVDUnQrZzNST042ZzdL
            WXF6dThTME1nVUVHVXI3R3FNajdGeXMKt6/liEnDRClLBvYSSYeM18s2XsB2ajz0
            aLQnXf1zOga7DG7XJNiHYpNx65SFHin3rz0rBowVi1FrrhCwbKPxGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j8rjscrrgm5jyl29peh5gqnmxx9qv795msdat33aa7qu3kqe5eysstlzzr
    lastmodified: "2026-07-16T22:18:28Z"
    mac: ENC[AES256_GCM,data:kqlGjNqwQ3mHJwMk9q8wkrwNmPerxCMBMXzAiTdAAs1FCfP7+xI0Tl1I2yZc22eg9qea4YRgLeJfiNLp4Pi+ZRAycMrvmugNm/s5sAdssvR+jA+s51/BFA4UJ4+abk4lSjcH8Z7/ocHx3LQ+hNGqrxeTJum0+BwV1yQa4A132+k=,iv:6kAfme/VCr98TUfOSO3emSsW4BZbLcIhyPPLrvEmQpM=,tag:qc6AGtS02f5brZZ2gfBMdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
