apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  selector:
    app: backend-api
  ports:
    - port: {{ .Values.backend.port | int }}
      targetPort: {{ .Values.backend.port | int }}
  type: ClusterIP