name: Deploy (k8s)

on:
  workflow_call:
    inputs:
      image_sha:
        required: true
        type: string
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
 
      - name: Install Helm
        uses: azure/setup-helm@v4
      
      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: "latest"

      - name: Install Helm Secrets Plugin
        run: 'helm plugin install https://github.com/jkroepke/helm-secrets --verify=false || true'
  
      - name: Deploy with Helm
        env:
          IMAGE: ${{ inputs.image_sha }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          helm upgrade backend-api ./helm/backend-api \
            --install \
            --namespace default \
            -f ./helm/backend-api/values.yaml \
            -f secrets://helm/backend-api/secrets.yaml \
            --set image.name="$IMAGE" \
            --wait \
            --timeout 4m \
