name: CI/CD Pipeline (k8s)
 
on:
  push:
    branches: [main]
 
jobs:
  checks:
    uses: ./.github/workflows/pr-checks.yml

  build:
    needs: [checks]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy-argocd.yml
    with:
      helm_path: HelmCharts/backend-api/values-production.yaml
      image_name: ${{ needs.build.outputs.image_sha }}
      branch: main
      gitops_repo: gpasha/argocd-lessons
      argocd_app_name: backend-api
      argocd_server: ${{ vars.ARGOCD_SERVER }}
    secrets:
      gitops_token: ${{ secrets.GITOPS_TOKEN }}
      argocd_auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}

  notify:
    needs: [checks, build, deploy]
    if: always()
    uses: ./.github/workflows/notify.yml
    with:
      checks_result: ${{ needs.checks.result }}
      build_result: ${{ needs.build.result }}
      deploy_result: ${{ needs.deploy.result }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}